---
title: "Simple document"
output: html_document
---

I'm an R Markdown document! 

# Section 1

Here's a **code chunk** that samples from 
a _normal distribution_:

```{r}
litters_data = read_csv(file = "./FAS_litters.csv")
#I (almost always) use janitor::clean_names() to clean up variable names after importing data. Doing so will take whatever the column names are and convert them to lower snake case.
names(litters_data)
litters_data = janitor::clean_names(litters_data)
names(litters_data)
#The package::function syntax lets you use a function from a package without loading the whole library. That’s really helpful, because some packages have functions with the same name (e.g. dplyr::filter and stats::filter), and R has to choose which one you mean. In general, only load the packages you need to prevent this kind of confusion. You can even use the conflicted package if you want to force yourself into using good habits!
pups_data = read_csv("./FAS_pups.csv")
pups_data
pups_data = janitor::clean_names(pups_data)
names(pups_data)
#In addition to printing the data (which is my first step), I often use View / view, str, head, and tail:
#
# Shorthand	Meaning
# ~	Home directory
# .	Current working directory
# ..	One directory up from current working directory
# ../..	Two directories up from current working directory
#Command + Shift + C change from code to comment
litters_data
tail(litters_data, 5)
skimr::skim(litters_data) 
view(litters_data)
# col_names: usually TRUE. If FALSE, column names are X1, X1, … . You can also supply column names.
# na: string vector containing character expressions for missing values.
# skip: number of rows to skip before reading data.
litters_data = read_csv(file = "./FAS_litters.csv",
  skip = 10, col_names = FALSE)
litters_data
head(litters_data)
#In some cases, though, you’ll want to give explicit column specifications. This is done using the cols function, and each column is given a column type
litters_data = read_csv(file = "./FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    "GD of Birth" = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
tail(litters_data)

litters_data = read_csv(file = "./FAS_litters.csv",
  col_types = "ccddiiii"
)
litters_data

library(readxl)
mlb11_data = read_excel("./mlb11.xlsx", n_max = 20)
head(mlb11_data, 5)

# The last tidyverse package for data import we’ll note is haven, which is used to import into R data files from SAS, Stata, and SPSS. An example for reading data from SAS follows.
library(haven)
pulse_data = read_sas("./public_pulse_data.sas7bdat")
head(pulse_data, 5)
```



```{r}
#library(tidyverse)
samp = rnorm(100)
length(samp)
#getwd()
#"./FAS_litters.csv"
```

# Section 2

I can take the mean of the sample, too!
The mean is `r mean(samp)`.